# Generated by Django 4.0.5 on 2022-07-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_email_alter_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empinsert',
        ),
    ]
