# Generated by Django 4.0.5 on 2022-08-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
