# Generated by Django 4.0.5 on 2022-08-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_post',
        ),
    ]
