# Generated by Django 4.0.5 on 2022-08-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_post_username_alter_post_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
