# Generated by Django 4.0.5 on 2022-08-17 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_post_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
