# Generated by Django 4.0.5 on 2022-08-17 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_likespost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likespost',
            name='likes_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
