# Generated by Django 4.0.5 on 2022-08-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_likespost_likes_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='likespost',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
        migrations.AlterField(
            model_name='likespost',
            name='post_id',
            field=models.CharField(max_length=100),
        ),
    ]
