# Generated by Django 4.0.5 on 2022-08-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.CharField(max_length=30)),
                ('user_to', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('post_id', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('new_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
