# Generated by Django 4.0.5 on 2022-08-31 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('from_username', models.CharField(max_length=30)),
                ('to_username', models.CharField(max_length=30)),
                ('sends_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
