# Generated by Django 4.0.5 on 2022-09-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='messages',
            field=models.IntegerField(default=0),
        ),
    ]
